version: '3.8'

services:
  frontend:
    image: node:20-alpine
    working_dir: /home/app
    ports:
      - "80:4200"
    command: sh -c "npm install -g @angular/cli@19 && npm install && ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules

  backend:
    image: maven:3.8.4-openjdk-17-slim
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dspring.devtools.restart.enabled=true"

  db:
    image: postgres:15.5
    environment:
      POSTGRES_DB: WEB_II
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
